### ISSUE TITLE
Questions about the torch version code

### ISSUE THREAD

**Issue by zzyo-yu** [akaxlh/SHT#1]
Your work is great, but when I was studying your code, I didn't find the attention calculation operation in equation (3) of the paper in the torch version, maybe I overlooked the corresponding code. I wish I could get your help, thank you very much!

**Comment by akaxlh** [comment]
Hello, and thank you for your intereset in this work.

I think you have correctly understood the code. The original implementation is in TensorFlow. When implementing the pyTorch version recently, we want to emphasize the proposed denoising self-supervised learning method, thus the sophiscated hypergraph transformer designs were omitted. If you are interested in the hypergraph transformer, you may also refer to the TensorFlow code.
