### ISSUE TITLE
baseline模型测试

### ISSUE THREAD

**Issue by yuanzhongfei** [akaxlh/SHT#2]
想问下这个baseline测试如何做的，以及参数设置，谢谢

**Comment by akaxlh** [comment]
你好，这篇工作的baseline测试是在tensorflow版本的训练测试框架下做的，现在已经弃用这个代码框架了，需要实现baseline的话可以考虑使用我们组的SSLRec: https://github.com/HKUDS/SSLRec

**Comment by yuanzhongfei** [comment]
> 你好，这篇工作的baseline测试是在tensorflow版本的训练测试框架下做的，现在已经弃用这个代码框架了，需要实现baseline的话可以考虑使用我们组的SSLRec: https://github.com/HKUDS/SSLRec

好的 谢谢

**Comment by yuanzhongfei** [comment]
> > 你好，这篇工作的baseline测试是在tensorflow版本的训练测试框架下做的，现在已经弃用这个代码框架了，需要实现baseline的话可以考虑使用我们组的SSLRec: https://github.com/HKUDS/SSLRec
> 
> 好的 谢谢

昨天用了sslrec测了下，这个sslrec那篇论文里面说的是各个模型的参数已经是最优的，我使用了SHT论文的数据集，好像结果差距有点大，不知道当时您们的参数如何调的呢，方便提供下其他一些模型的一些参数么，我想做一些对比实验。谢谢
