### ISSUE TITLE
baseline参数

### ISSUE THREAD

**Issue by yuanzhongfei** [akaxlh/SHT#3]
昨天用了您发的那个sslrec测了下，这个sslrec那篇论文里面说的是各个模型的参数已经是最优的，我就没有调节，我使用了SHT论文的数据集（yelp，用的lightgcn），好像结果差距有点大，不知道当时您们的参数如何调的呢？谢谢

**Comment by akaxlh** [comment]
您好，如果需要哪份tensorflow版本的baseline实现和当时的参数设置可以发邮件给我，我找一下发给你。SSLRec中的实现对特定数据集的结果可能还需要调参。在同方法、同数据集的情况下，效果应该更高。

**Comment by akaxlh** [comment]
您好，不知道您是调出来SSLRec结果更高还是更低。更低的话，SSLRec中的代码应该只是对特定数据集调过参，可能在您试的这个数据集上还需要调整。更高的话，SSLRec中更新了训练loss计算方式等地方，效果本身应该会更好。另外，sslrec中release的yelp数据集并不是SHT这篇工作使用的yelp，会更加稀疏。如果需要哪份tensorflow版本的baseline实现和当时的参数设置可以发邮件给我，我找一下发给您。

**Comment by yuanzhongfei** [comment]
昨天用的数据集是您这边论文的yelp，使用SSLRec跑的lightGCN模型，结果比论文的更高。我想要下 NGCF，lightGCN，SGL，MHCN的。谢谢

**Comment by akaxlh** [comment]
OK，您的邮箱是多少呢？

**Comment by yuanzhongfei** [comment]
2714703817@qq.com 非常感谢
